builders:
  clear_insight_generator:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:clear_insight_generator/core.dart"
    # Name of the function in the above library to call.
    builder_factories: ["clearInsightBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: { ".dart": [".clear.dart"] }
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly into the package, not to a hidden cache dir
    build_to: source
    defaults:
      options:
          project_id: "WOW"