name: clear_insight_generator
description: An generator for Clear Insight analytics
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  source_gen: ^1.4.0
  http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  very_good_analysis: ^5.0.0
